export const setUserId = userId => ({type: 'SET_USER_ID', userId })
export const unsetUserId = () => ({type: 'UNSET_USER_ID' })
export const dataLoaded = () => ({type: 'SET_LOADING_STATE', value: false})
export const setStartDate = (startDate) => ({type: 'SET_RESERVATION_START_DATE', date: startDate})
export const setEndDate = (endDate) => ({type: 'SET_RESERVATION_END_DATE', date: endDate})
export const setInventory = (inventory) => ({type: 'SET_INVENTORY', payload: inventory})
